version: '3.7'

services:

  weatherapp:
    image: emonidi/weatherapp:latest
    container_name: weatherapp
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 80:80
  nginx:
    container_name: nginx
    restart: always
    image: nginx:alpine
    ports:
      - 3001:3001
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf:rw
volumes:
  nginx:
