version: '3.7'

services:

  weatherapp:
    image: emonidi/weatherapp:latest
    container_name: weatherapp
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 80:80
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf:rw
volumes:
  nginx:
